documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - package-lock.json

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

app:
  - changed-files:
      - any-glob-to-any-file: 'src/**'

config:
  - changed-files:
      - any-glob-to-any-file:
          - app.json
          - eas.json
          - tsconfig.json
          - eslint.config.js
          - .prettierrc.json
